# Generated by Django 3.2.5 on 2021-07-28 09:53

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('documents', '0024_document_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('website',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapy_item_website',
                                   to='documents.website')),
            ],
        ),
    ]
