version: '3'
services:
  django:
    build: ./backend
    env_file:
      - ./secrets/django-docker.env
    volumes:
    - ./backend:/backend
    command: ./start.sh
    restart:
      always
    ports:
      - "8000:8000"
    depends_on:
      - occ_postgres
      - occ_minio
      - celery

  react:
    build: ./frontend
    volumes:
    - ./frontend:/frontend
    - /frontend/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true


  # Not working yet!! Fix later for production
  django_nginx:
    restart: always
    build: ./backend/nginx
    depends_on:
      - django


  occ_postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/django-docker.env
    volumes:
      - occ_postgres:/var/lib/postgresql/data

  occ_minio:
    image: minio/minio
    command: server /data
    ports:
      - "19000:9000"
    env_file:
      - ./secrets/django-docker.env
    volumes:
      - occ_minio:/data

  celery:
    build: ./backend
    command: celery -A scheduler worker -l info
    volumes:
      - ./backend:/backend
    env_file:
      - ./secrets/django-docker.env
    restart:
      always
    depends_on:
      #      - django
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    env_file:
      - ./secrets/django-docker.env
    ports:
      - "5672:5672"


volumes:
  occ_postgres:
  occ_minio: