version: '3'
services:
  django:
    image: docker.crosslang.com/occam_doc_manager/django:develop-latest
    restart:
      always
    env_file:
      - ./secrets/django-docker.env
    command: ./start.sh
    depends_on:
      - occ_postgres
      - occ_minio
      - celery
    networks:
      - default

  react:
    image: docker.crosslang.com/occam_doc_manager/react:develop-latest
    restart: always
    env_file:
      - ./secrets/django-docker.env
    depends_on:
      - django
    networks:
      - default
    labels:
      - traefik.http.routers.react.rule=Host(`react.staging.occam.crosslang.com`)
      - traefik.http.routers.react.tls=true
      - traefik.http.routers.react.tls.certresolver=le
      - traefik.http.routers.react.entrypoints=websecure
    volumes:
      - ./secrets/react.env:/usr/share/nginx/html/.env

  django_nginx:
    image: docker.crosslang.com/occam_doc_manager/django_nginx:develop-latest
    expose: [8000]
    restart: always
    depends_on:
      - django
    networks:
      - default
    labels:
      - traefik.http.routers.django.rule=Host(`django.staging.occam.crosslang.com`)
      - traefik.http.routers.django.tls=true
      - traefik.http.routers.django.tls.certresolver=le
      - traefik.http.routers.django.entrypoints=websecure
      - traefik.http.services.django.loadbalancer.server.port=8000

  celery:
    image: docker.crosslang.com/occam_doc_manager/django:develop-latest
    command: celery -A scheduler worker -l info
    restart:
      always
    env_file:
      - ./secrets/django-docker.env
    depends_on:
      - rabbitmq
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  rabbitmq:
    image: rabbitmq:3.8
    env_file:
      - ./secrets/django-docker.env
    networks:
      - default

  occ_postgres:
    image: postgres:13
    restart: always
    env_file:
      - ./secrets/django-docker.env
    volumes:
      - /mnt/HC_Volume_123777/occam_doc_manager/postgres:/var/lib/postgresql/data
    networks:
      - default

  occ_minio:
    image: minio/minio:RELEASE.2021-08-31T05-46-54Z
    restart: always
    command: server /data --console-address ":9001"
    env_file:
      - ./secrets/django-docker.env
    volumes:
      - /mnt/HC_Volume_123777/occam_doc_manager/minio:/data
    networks:
      - default
    ports:
      - 9000:9000
      - 9001:9001
    labels:
      - traefik.http.routers.minioConsole.rule=Host(`console.minio.staging.occam.crosslang.com`)
      - traefik.http.routers.minioConsole.tls=true
      - traefik.http.routers.minioConsole.tls.certresolver=le
      - traefik.http.routers.minioConsole.entrypoints=websecure
      - traefik.http.routers.minioConsole.service=minioConsoleService
      - traefik.http.services.minioConsoleService.loadbalancer.server.port=9001
      - traefik.http.routers.minio.rule=Host(`minio.staging.occam.crosslang.com`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=le
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.service=minioService
      - traefik.http.services.minioService.loadbalancer.server.port=9000


  scrapyd:
    image: docker.crosslang.com/occam_doc_manager/django:develop-latest
    ports:
      - "6800:6800"
    env_file:
      - ./secrets/django-docker.env
    working_dir: /backend/scrapy_app
    command: scrapyd
#    labels:
#      - traefik.http.routers.scrapy.rule=Host(`scrapy.staging.occam.crosslang.com`)
#      - traefik.http.routers.scrapy.tls=true
#      - traefik.http.routers.scrapy.tls.certresolver=le
#      - traefik.http.routers.scrapy.entrypoints=websecure

networks:
  default:
    external:
      name: gateway