# Generated by Django 3.2 on 2021-04-20 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20210420_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Waiting on start of layout analysis.', 'Waiting Layout Analysis'), ('Running layout analysis.', 'Running Layout Analysis'), ('Layout analysis completed.', 'Completed Layout Analysis'), ('Waiting on start of OCR.', 'Waiting Ocr'), ('Running OCR.', 'Running Ocr'), ('OCR completed.', 'Completed Ocr')], default='New', max_length=50),
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('translation_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_overlay', to='documents.page')),
            ],
        ),
    ]
