# Generated by Django 3.2 on 2021-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210420_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='geojson',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Waiting on start of layout analysis.', 'Waiting Layout Analysis'), ('Running layout analysis.', 'Running Layout Analysis'), ('Layout analysis completed.', 'Completed Layout Analysis'), ('Waiting on start of OCR.', 'Waiting Ocr'), ('Running OCR.', 'Running Ocr'), ('OCR completed.', 'Completed Ocr')], default='New', max_length=50),
        ),
    ]
