# Generated by Django 3.2 on 2021-04-30 13:06

from django.db import migrations, models

from documents.models import Overlay


def fix_geojsons(apps, schema_editor):
    # Overlay = apps.get_model("documents", "Overlay")

    for obj in Overlay.objects.all():
        try:
            obj.create_geojson()
        except Exception as e:
            print(e)
            print(f'Failed to generate geojson for {obj}.\nFile: {obj.file}')
        else:
            print('Success!')


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0008_auto_20210430_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlay',
            name='geojson',
        ),
    ]

    operations = [migrations.RunPython(fix_geojsons)]
