# Generated by Django 3.2.2 on 2021-05-12 12:11

from django.db import migrations

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0011_auto_20210512_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='source_lang',
            field=documents.models.LangField(
                choices=[('NL', 'Nederlands'), ('EN', 'English'), ('FR', 'Français'), ('DE', 'Deutsch')], default='EN',
                max_length=2),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='geojson',
            name='source_lang',
        ),
    ]
