# Generated by Django 3.2 on 2021-05-12 15:10

from django.db import migrations

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0012_auto_20210512_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojson',
            name='lang',
            field=documents.models.LangField(
                choices=[('NL', 'Nederlands'), ('EN', 'English'), ('FR', 'Français'), ('DE', 'Deutsch'),
                         ('CS', 'Čeština')], max_length=2),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='source_lang',
            field=documents.models.LangField(
                choices=[('NL', 'Nederlands'), ('EN', 'English'), ('FR', 'Français'), ('DE', 'Deutsch'),
                         ('CS', 'Čeština')], max_length=2),
        ),
    ]
