# Generated by Django 3.2.3 on 2021-06-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0017_auto_20210604_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='labels',
        ),
        migrations.AddField(
            model_name='label',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='page_labels',
                                    to='documents.page'),
            preserve_default=False,
        ),
    ]
