# Generated by Django 3.2.3 on 2021-06-07 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0018_auto_20210604_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
    ]
