# Generated by Django 3.2.3 on 2021-06-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0020_auto_20210622_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='layout_analysis_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='documents.layoutanalysismodel'),
        ),
    ]
