# Generated by Django 3.2.5 on 2021-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0022_layout_analysis_engine_add_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
