# Generated by Django 3.2.5 on 2021-07-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0023_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='documents.website'),
        ),
    ]
