# Generated by Django 3.2.6 on 2021-09-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_document_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Europeana', 'Europeana')], default='Manual', max_length=20),
        ),
    ]
