# Generated by Django 3.2.6 on 2021-08-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_document_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['created_at']},
        ),
    ]
