# Generated by Django 3.2.6 on 2021-09-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_alter_page_options'),
        ('documents', '0026_document_europeana_item_id'),
    ]

    operations = [
    ]
