# Generated by Django 3.2.6 on 2021-09-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_merge_20210908_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
    ]
