# Generated by Django 3.2.6 on 2021-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_remove_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='europeana_item_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
