# Generated by Django 3.2.6 on 2021-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_document_oaipmh_item_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='oaipmh_item_id',
            new_name='oaipmh_collection_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='oaipmh_item_url',
        ),
        migrations.AddField(
            model_name='document',
            name='oaipmh_collection_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
