# Generated by Django 3.2.6 on 2021-09-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_metadata'),
        ('documents', '0032_auto_20210914_0920'),
    ]

    operations = [
    ]
