# Generated by Django 3.2.6 on 2021-09-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_merge_0030_metadata_0032_auto_20210914_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='right',
            new_name='rights',
        ),
    ]
