# Generated by Django 3.2.6 on 2021-09-21 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_rename_right_metadata_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('certainty', models.TextField(blank=True, default='')),
                ('prediction', models.BooleanField(blank=True, null=True)),
                ('label', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_doc_type_pred', to='documents.page')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='layoutanalysismodel',
            options={'ordering': ['pk']},
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
