# Generated by Django 3.2.6 on 2021-09-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_auto_20210921_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttypeprediction',
            name='certainty',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='documenttypeprediction',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='documenttypeprediction',
            name='label',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
