# Generated by Django 3.2.6 on 2021-08-23 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtrCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_number', models.CharField(default='', max_length=100, unique=True)),
                ('date_of_creation_and_registration', models.CharField(default='', max_length=100)),
                ('file_number', models.CharField(default='', max_length=100)),
                ('trading_company', models.CharField(default='', max_length=100)),
                ('legal_form', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CTR Companies',
            },
        ),
        migrations.CreateModel(
            name='StatutoryAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_company_statutory_authorities', to='ctr.ctrcompany')),
            ],
            options={
                'verbose_name_plural': 'Statutory Authorities',
            },
        ),
        migrations.CreateModel(
            name='ScopeOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_company_scope_of_businesses', to='ctr.ctrcompany')),
            ],
            options={
                'verbose_name_plural': 'Scope of businesses',
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_company_residences', to='ctr.ctrcompany')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_company_other_facts', to='ctr.ctrcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion', models.CharField(default='', max_length=100)),
                ('share', models.CharField(default='', max_length=100)),
                ('lien', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_company_companions', to='ctr.ctrcompany')),
            ],
        ),
    ]
