# Generated by Django 3.2.6 on 2021-09-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctr', '0004_auto_20210902_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctrcompany',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='ctrcompany',
            name='trading_company',
        ),
    ]
