# Generated by Django 3.2 on 2021-05-18 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0013_auto_20210512_1510'),
        ('activitylogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OCR', 'Ocr'), ('Translation', 'Translation')], max_length=50)),
                ('state', models.CharField(
                    choices=[('Created', 'Created'), ('Waiting', 'Waiting'), ('Started', 'Started'),
                             ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Success', 'Success')],
                    default='Created', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_page',
                                   to='documents.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='page',
        ),
        migrations.DeleteModel(
            name='OcrRequest',
        ),
        migrations.DeleteModel(
            name='TranslationRequest',
        ),
    ]
