# Generated by Django 3.2 on 2021-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activitylogs', '0002_auto_20210518_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='state',
            field=models.CharField(choices=[('Created', 'Created'), ('Waiting', 'Waiting'), ('Started', 'Started'),
                                            ('Processing', 'Processing'), ('Failed', 'Failed'), ('Success', 'Success')],
                                   default='Created', max_length=50),
        ),
    ]
