# Generated by Django 3.2.3 on 2021-06-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activitylogs', '0005_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='state',
            field=models.CharField(
                choices=[('Created', 'Created'), ('Classified', 'Classified'), ('Waiting', 'Waiting'),
                         ('Started', 'Started'), ('Processing', 'Processing'), ('Failed', 'Failed'),
                         ('Success', 'Success')], default='Created', max_length=50),
        ),
    ]
