# Generated by Django 3.2.6 on 2021-08-11 12:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_number', models.CharField(default='', max_length=100, unique=True)),
                ('state', models.CharField(default='', max_length=100)),
                ('legal_status', models.TextField(blank=True, default='')),
                ('start_date', models.CharField(default='', max_length=100)),
                ('name', models.TextField(default='')),
                ('address', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('fax_number', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=1000)),
                ('entity_type', models.CharField(blank=True, default='', max_length=1000)),
                ('legal_form', models.CharField(blank=True, default='', max_length=1000)),
                ('capital', models.CharField(blank=True, default='', max_length=1000)),
                ('annual_meeting', models.CharField(blank=True, default='', max_length=1000)),
                ('fiscal_year_end_date', models.CharField(blank=True, default='', max_length=1000)),
                ('start_date_exceptional_financial_year', models.CharField(blank=True, default='', max_length=1000)),
                ('end_date_exceptional_financial_year', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='RszNacebelActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='company_rsz_nacebel_activities', to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='company_professional_competencies', to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permits',
                                   to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='company_links_between_entities', to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('job_holder', models.CharField(default='', max_length=1000)),
                ('date', models.CharField(default='', max_length=100)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_functions',
                                   to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('url', models.URLField(default='')),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_external_links',
                                   to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='BtwNacebelActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='company_btw_nacebel_activities', to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='BranchUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_branch_units',
                                   to='kbo.company')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_attributes',
                                   to='kbo.company')),
            ],
        ),
    ]
