# Generated by Django 3.2.6 on 2021-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedentity',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
