# Generated by Django 3.2.6 on 2021-08-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kbo', '0002_linkedentity_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_directors',
                                   to='kbo.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
