# Generated by Django 3.2.6 on 2021-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kbo', '0003_auto_20210812_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='role',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
